---
# tasks file for samba_server
- name: install software packages
  package:
    name:
      - samba
      - samba-client
      - samba-common    
    state: present

- name: install SElinux package
  yum:
    name: python3-policycoreutils.noarch
    state: present

- name: create shared directory
  file:
    path: "{{ share_directory }}"
    state: directory
    mode: "777"
    setype: samba_share_t

- name: setup SELinux type persistently for shared directory
  sefcontext:
    target: "{{ share_directory }}(/.*)?"
    setype: samba_share_t
    state: present

- name: restore context
  shell: restorecon -Rv {{ share_directory }}

- name: configure shared directory
  blockinfile:
    path: /etc/samba/smb.conf
    block: "{{ lookup('template', '../templates/smb.conf.j2') }}"
    # validate: testparm
  notify:
    - start services

- name: allow firewall rule for samba
  ansible.posix.firewalld:
    service: samba
    permanent: yes
    state: enabled
    immediate: true
  ignore_errors: true

- name: create samba accounts
  shell: |
    (echo {{ item.password }}; echo {{ item.password }}) | smbpasswd -a {{ item.key }} -s
  when: samba_users is defined and len(samba_users) > 1
  loop: "{{ samba_users   }}"
  
